"use client";

import { MitraNav } from "@/components/mitra/mitra-nav";
import { usePhase10Mitra } from "@/lib/store/phase10-mitra-store";
import { formatIndonesianDate, formatRupiah } from "@/lib/utils";
import { BadgeCheck, Banknote, CheckCircle2, Clock, Download, MessageSquare, ShieldCheck, Star, UserCheck, Wallet } from "lucide-react";
function Shell({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <div className="min-h-screen bg-slate-50 text-slate-800"><MitraNav currentTab="keuangan"/><main className="max-w-7xl mx-auto px-4 sm:px-6 py-6 space-y-6"><div><span className="inline-flex px-3 py-1 rounded-full bg-blue-50 text-blue-700 border border-blue-200 text-xs font-bold mb-3">Fase 10 Mitra</span><h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-slate-950">{title}</h1><p className="text-sm text-slate-500 mt-1 max-w-3xl">{subtitle}</p></div>{children}</main></div> }
function Card({children}: {children: React.ReactNode}) { return <section className="bg-white rounded-3xl border border-slate-200 p-6 shadow-xs">{children}</section> }
function Money({ value }: { value: number }) { return <span className="font-mono font-extrabold tabular-nums">{formatRupiah(value)}</span> }

export default function DanaPage(){ const { payouts } = usePhase10Mitra(); const total = payouts.reduce((s,p)=>s+p.netPayout,0); return <Shell title="Dashboard Keuangan Dana Saya" subtitle="Transparansi posisi dana sewa: ditahan escrow, dijadwalkan cair H+1, sampai berhasil ditransfer ke rekening bank mitra."><div className="grid md:grid-cols-3 gap-4"><Card><Wallet className="w-6 h-6 text-blue-600"/><p className="text-xs font-bold text-slate-500 mt-4">Total ledger</p><p className="text-2xl text-slate-950"><Money value={total}/></p></Card><Card><Clock className="w-6 h-6 text-amber-600"/><p className="text-xs font-bold text-slate-500 mt-4">Menunggu H+1</p><p className="text-2xl font-extrabold text-slate-950">2 Transaksi</p></Card><Card><CheckCircle2 className="w-6 h-6 text-emerald-600"/><p className="text-xs font-bold text-slate-500 mt-4">Transfer sukses</p><p className="text-2xl font-extrabold text-slate-950">1 Transaksi</p></Card></div><Card><h2 className="font-extrabold text-slate-950 mb-4">Ledger payout immutable</h2><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs text-slate-500 border-b"><th className="py-3">Booking</th><th>Unit</th><th>Status</th><th>Cair</th><th className="text-right">Net payout</th></tr></thead><tbody>{payouts.map((p)=><tr key={p.id} className="border-b border-slate-100"><td className="py-4 font-mono font-bold">{p.bookingCode}</td><td>{p.vehicleName}</td><td><span className="px-2 py-1 rounded-full bg-blue-50 text-blue-700 text-[11px] font-bold">{p.status.replaceAll("_"," ")}</span></td><td>{formatIndonesianDate(p.escrowReleaseAt)}</td><td className="text-right"><Money value={p.netPayout}/></td></tr>)}</tbody></table></div></Card></Shell> }
