"use client";

import { MitraNav } from "@/components/mitra/mitra-nav";
import { usePhase10Mitra } from "@/lib/store/phase10-mitra-store";
import { formatIndonesianDate, formatRupiah } from "@/lib/utils";
import { BadgeCheck, Banknote, CheckCircle2, Clock, Download, MessageSquare, ShieldCheck, Star, UserCheck, Wallet } from "lucide-react";
function Shell({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <div className="min-h-screen bg-slate-50 text-slate-800"><MitraNav currentTab="keuangan"/><main className="max-w-7xl mx-auto px-4 sm:px-6 py-6 space-y-6"><div><span className="inline-flex px-3 py-1 rounded-full bg-blue-50 text-blue-700 border border-blue-200 text-xs font-bold mb-3">Fase 10 Mitra</span><h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-slate-950">{title}</h1><p className="text-sm text-slate-500 mt-1 max-w-3xl">{subtitle}</p></div>{children}</main></div> }
function Card({children}: {children: React.ReactNode}) { return <section className="bg-white rounded-3xl border border-slate-200 p-6 shadow-xs">{children}</section> }
function Money({ value }: { value: number }) { return <span className="font-mono font-extrabold tabular-nums">{formatRupiah(value)}</span> }

export default function LaporanPage(){ const { payouts } = usePhase10Mitra(); const gross = payouts.reduce((s,p)=>s+p.grossAmount,0); const fee = payouts.reduce((s,p)=>s+p.platformFee,0); return <Shell title="Rekapitulasi Pembukuan & Laporan Unduhan" subtitle="Ringkasan pendapatan bersih, potongan komisi platform, dan ekspor laporan bulanan untuk pembukuan rental."><div className="grid md:grid-cols-3 gap-4"><Card><p className="text-xs font-bold text-slate-500">Pendapatan bruto</p><p className="text-2xl text-slate-950 mt-2"><Money value={gross}/></p></Card><Card><p className="text-xs font-bold text-slate-500">Komisi platform</p><p className="text-2xl text-slate-950 mt-2"><Money value={fee}/></p></Card><Card><p className="text-xs font-bold text-slate-500">Pendapatan bersih</p><p className="text-2xl text-slate-950 mt-2"><Money value={gross-fee}/></p></Card></div><Card><h2 className="font-extrabold text-slate-950 mb-4">Unduh laporan</h2><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">{["CSV mutasi", "PDF ringkasan", "CSV pajak", "Audit escrow"].map((x)=><button key={x} className="min-h-[44px] rounded-2xl border border-slate-200 hover:bg-slate-50 text-sm font-extrabold flex items-center justify-center gap-2"><Download className="w-4 h-4 text-blue-600"/>{x}</button>)}</div></Card></Shell> }
