import { Vehicle, PickupSpot } from "@/types/domain";

export const YOGYAKARTA_PICKUP_SPOTS: PickupSpot[] = [
  {
    id: "spot-yia",
    name: "Bandara Internasional Yogyakarta (YIA)",
    code: "YIA",
    area: "Kulon Progo",
    description: "Zona Penjemputan Terminal Kedatangan / Drop-off Area",
    extraFee: 100000,
    isPopular: true,
    estimatedDeliveryMin: 45,
  },
  {
    id: "spot-tugu",
    name: "Stasiun Tugu Yogyakarta",
    code: "YK-TUGU",
    area: "Kota Yogyakarta (Pusat)",
    description: "Pintu Selatan (Jl. Pasar Kembang) & Pintu Barat Bong Suwung",
    extraFee: 0,
    isPopular: true,
    estimatedDeliveryMin: 15,
  },
  {
    id: "spot-lempuyangan",
    name: "Stasiun Lempuyangan",
    code: "YK-LPN",
    area: "Danurejan, Kota Yogyakarta",
    description: "Drop-off Zone Pintu Timur Jl. Lempuyangan",
    extraFee: 0,
    isPopular: true,
    estimatedDeliveryMin: 20,
  },
  {
    id: "spot-malioboro",
    name: "Kawasan Malioboro & Sosrowijayan",
    code: "YK-MLBR",
    area: "Gedongtengen, Kota Yogyakarta",
    description: "Lobi Hotel / Titik Temu Area Malioboro",
    extraFee: 0,
    isPopular: true,
    estimatedDeliveryMin: 15,
  },
  {
    id: "spot-sleman",
    name: "Garasi Mitra Sleman (Jl. Magelang)",
    code: "SLM-MLT",
    area: "Mlati, Sleman",
    description: "Jl. Magelang Km 7.5, Mlati, Sleman",
    extraFee: 0,
    isPopular: false,
    estimatedDeliveryMin: 0,
  },
  {
    id: "spot-bantul",
    name: "Garasi Mitra Bantul (Jl. Bantul)",
    code: "BTL-SWN",
    area: "Sewon, Bantul",
    description: "Jl. Bantul Km 5.5, Sewon, Bantul",
    extraFee: 0,
    isPopular: false,
    estimatedDeliveryMin: 0,
  },
];

export const FEATURED_YOGYAKARTA_VEHICLES: Vehicle[] = [
  {
    id: "veh-zenix-01",
    rentalId: "rental-tugu",
    rentalName: "Tugu Rent Jogja",
    rentalRating: 4.97,
    rentalCompletedBookings: 642,
    name: "Toyota Innova Zenix 2.0 Q Hybrid TSS 2024",
    brand: "Toyota",
    model: "Innova Zenix Hybrid",
    year: 2024,
    licensePlate: "AB 1001 QZ",
    category: "MPV",
    transmission: "CVT",
    fuelType: "HYBRID",
    seatingCapacity: 7,
    luggageCapacity: 4,
    engineCapacityCc: 1987,
    features: [
      "Toyota Safety Sense 3.0",
      "Panoramic Sunroof",
      "Captain Seat Ottoman Elektrik",
      "Wireless Apple CarPlay & Android Auto",
      "Kamera 360 Derajat",
    ],
    thumbnailUrl:
      "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1200&q=80",
    ],
    status: "TERSEDIA",
    baseDailyRate: 650000,
    securityDeposit: 250000,
    deliveryFee: 0,
    city: "Kota Yogyakarta",
    district: "Gedongtengen",
    garageAddress: "Jl. Sosrowijayan No. 42 (Dekat Stasiun Tugu)",
    lastUpdatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    isPopular: true,
  },
  {
    id: "veh-xforce-01",
    rentalId: "rental-sleman",
    rentalName: "Sleman Auto Perkasa",
    rentalRating: 4.93,
    rentalCompletedBookings: 388,
    name: "Mitsubishi Xforce Ultimate 1.5 CVT 2024",
    brand: "Mitsubishi",
    model: "Xforce Ultimate",
    year: 2024,
    licensePlate: "AB 1890 DX",
    category: "SUV",
    transmission: "CVT",
    fuelType: "BENSIN",
    seatingCapacity: 5,
    luggageCapacity: 3,
    engineCapacityCc: 1499,
    features: [
      "Yamaha Dynamic Sound Premium",
      "Drive Mode: Wet / Gravel / Mud / Normal",
      "Dual Zone AC Nanoe-X",
      "Blind Spot Warning & RCTA",
      "Ground Clearance 222 mm (Siap Merapi)",
    ],
    thumbnailUrl:
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
    ],
    status: "TERSEDIA",
    baseDailyRate: 550000,
    securityDeposit: 200000,
    deliveryFee: 0,
    city: "Sleman",
    district: "Mlati",
    garageAddress: "Jl. Magelang Km 7.5, Mlati",
    lastUpdatedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    isPopular: true,
  },
  {
    id: "veh-ioniq-01",
    rentalId: "rental-malioboro",
    rentalName: "Malioboro Trans Mobility",
    rentalRating: 4.95,
    rentalCompletedBookings: 472,
    name: "Hyundai Ioniq 5 Signature Long Range 2024",
    brand: "Hyundai",
    model: "Ioniq 5 Long Range",
    year: 2024,
    licensePlate: "AB 1555 EV",
    category: "EV",
    transmission: "AUTOMATIC",
    fuelType: "LISTRIK",
    seatingCapacity: 5,
    luggageCapacity: 4,
    engineCapacityCc: 0,
    features: [
      "Jarak Tempuh 451 KM Sekali Charge",
      "V2L (Vehicle to Load) Colokan 220V",
      "Hyundai SmartSense ADAS",
      "Vision Roof & Relax Comfort Seat",
      "Gratis Akses SPKLU Tertentu di Jogja",
    ],
    thumbnailUrl:
      "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=80",
    ],
    status: "TERSEDIA",
    baseDailyRate: 850000,
    securityDeposit: 350000,
    deliveryFee: 50000,
    city: "Kota Yogyakarta",
    district: "Gedongtengen",
    garageAddress: "Jl. Dagen No. 18, Malioboro",
    lastUpdatedAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    isPopular: true,
  },
  {
    id: "veh-avanza-01",
    rentalId: "rental-tugu",
    rentalName: "Tugu Rent Jogja",
    rentalRating: 4.97,
    rentalCompletedBookings: 642,
    name: "Toyota All New Avanza 1.5 G CVT TSS 2023",
    brand: "Toyota",
    model: "All New Avanza",
    year: 2023,
    licensePlate: "AB 1234 XY",
    category: "MPV",
    transmission: "CVT",
    fuelType: "BENSIN",
    seatingCapacity: 7,
    luggageCapacity: 3,
    engineCapacityCc: 1496,
    features: [
      "Sofa Mode Interior Nyaman",
      "Toyota Safety Sense (TSS)",
      "Rear Parking Camera & Sensor",
      "Irit BBM Konsumsi 1:16 KM/L",
      "AC Double Blower Dingin Merata",
    ],
    thumbnailUrl:
      "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80",
    ],
    status: "TERSEDIA",
    baseDailyRate: 400000,
    securityDeposit: 150000,
    deliveryFee: 0,
    city: "Kota Yogyakarta",
    district: "Gedongtengen",
    garageAddress: "Jl. Sosrowijayan No. 42",
    lastUpdatedAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    isPopular: true,
  },
  {
    id: "veh-brio-01",
    rentalId: "rental-kencana",
    rentalName: "Kencana Rent Jogja Selatan",
    rentalRating: 4.89,
    rentalCompletedBookings: 295,
    name: "Honda Brio RS Urbanite Edition CVT 2023",
    brand: "Honda",
    model: "Brio RS Urbanite",
    year: 2023,
    licensePlate: "AB 1420 JK",
    category: "CITY_CAR",
    transmission: "CVT",
    fuelType: "BENSIN",
    seatingCapacity: 5,
    luggageCapacity: 2,
    engineCapacityCc: 1199,
    features: [
      "Lincah Parkir di Gang Kota & Malioboro",
      "Audio Display Touchscreen",
      "Konsumsi BBM Sangat Irit (1:18 KM/L)",
      "Dual SRS Airbags & ABS EBD",
      "AC Digital Dingin Cepat",
    ],
    thumbnailUrl:
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80",
    ],
    status: "TERSEDIA",
    baseDailyRate: 350000,
    securityDeposit: 150000,
    deliveryFee: 0,
    city: "Bantul",
    district: "Sewon",
    garageAddress: "Jl. Bantul Km 5.5, Sewon",
    lastUpdatedAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    isPopular: false,
  },
  {
    id: "veh-fortuner-01",
    rentalId: "rental-sleman",
    rentalName: "Sleman Auto Perkasa",
    rentalRating: 4.93,
    rentalCompletedBookings: 388,
    name: "Toyota Fortuner 2.8 VRZ GR Sport 4x2 2024",
    brand: "Toyota",
    model: "Fortuner 2.8 GR Sport",
    year: 2024,
    licensePlate: "AB 1999 FZ",
    category: "SUV",
    transmission: "AUTOMATIC",
    fuelType: "DIESEL",
    seatingCapacity: 7,
    luggageCapacity: 4,
    engineCapacityCc: 2755,
    features: [
      "Mesin 1GD-FTV 204 PS Torsi 500 Nm",
      "Power Backdoor dengan Kick Sensor",
      "Suspensi GR Sport Nyaman di Tanjakan",
      "Wireless Charger & Rear Seat Entertainment",
      "Kamera 360 Panoramic View Monitor",
    ],
    thumbnailUrl:
      "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=80",
    ],
    status: "TERSEDIA",
    baseDailyRate: 1100000,
    securityDeposit: 500000,
    deliveryFee: 0,
    city: "Sleman",
    district: "Mlati",
    garageAddress: "Jl. Magelang Km 7.5",
    lastUpdatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    isPopular: false,
  },
];

export const YOGYAKARTA_RENTAL_PARTNERS: import("@/types/domain").RentalPartner[] = [
  {
    id: "rental-tugu",
    name: "Tugu Rent Jogja",
    slug: "tugu-rent-jogja",
    nib: "0220108921844",
    nibVerified: true,
    rating: 4.97,
    totalReviews: 142,
    completedBookings: 642,
    address: "Jl. Sosrowijayan No. 42, Sosromenduran, Gedongtengen",
    district: "Gedongtengen",
    city: "Kota Yogyakarta",
    phone: "+62 274 589 123",
    whatsapp: "+62 812 3456 7890",
    operatingHours: "06:00 - 23:00 WIB (Antar-Jemput 24 Jam)",
    description:
      "Mitra rental resmi berizin OSS-RBA dengan pengalaman 8 tahun di pusat kota Yogyakarta. Mengkhususkan armada MPV & mobil keluarga dengan perawatan berkala bengkel resmi Toyota. Titik garasi hanya 3 menit dari Stasiun Tugu Yogyakarta.",
    avatarUrl:
      "https://images.unsplash.com/photo-1560179707-f14e90ef3623?auto=format&fit=crop&w=300&q=80",
    bannerUrl:
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    establishedYear: 2017,
    coverageSpotIds: ["spot-tugu", "spot-yia", "spot-lempuyangan", "spot-malioboro"],
    features: [
      "Izin Usaha NIB OSS-RBA Terverifikasi",
      "Garansi Unit Bersih & Steril",
      "Layanan Antar-Jemput Stasiun Tugu & YIA",
      "Asuransi All Risk Komprehensif",
      "Dukungan Darurat 24 Jam",
    ],
    reviews: [
      {
        id: "rev-01",
        authorName: "Dimas Anggara",
        authorCity: "Jakarta Selatan",
        rating: 5,
        date: "28 September 2026",
        comment:
          "Zenix Hybrid sangat terawat! Mobil diantar tepat waktu di Stasiun Tugu pintu barat. AC sejuk, bau mobil baru, serah terima via digital checklist cepat sekali.",
        vehicleName: "Toyota Innova Zenix 2.0 Q Hybrid TSS 2024",
        merchantReply: {
          author: "Bambang Sudibyo (Owner Tugu Rent)",
          date: "28 September 2026",
          comment:
            "Matur nuwun Mas Dimas atas kepercayaannya! Senang sekali Zenix kami bisa menemani perjalanan keluarga di Jogja. Sampai jumpa di liburan berikutnya!",
        },
      },
      {
        id: "rev-02",
        authorName: "Sarah Wijaya",
        authorCity: "Surabaya",
        rating: 5,
        date: "15 September 2026",
        comment:
          "Sangat puas sewa Avanza di sini. Lepas kunci mudah dan verifikasi e-KYC DriveO langsung beres. CS ramah dan solutif waktu tanya rekomendasi rute ke Mangunan.",
        vehicleName: "Toyota All New Avanza 1.5 G CVT TSS 2023",
      },
    ],
  },
  {
    id: "rental-sleman",
    name: "Sleman Auto Perkasa",
    slug: "sleman-auto-perkasa",
    nib: "9120204719283",
    nibVerified: true,
    rating: 4.93,
    totalReviews: 98,
    completedBookings: 388,
    address: "Jl. Magelang Km 7.5, Sendangadi, Mlati",
    district: "Mlati",
    city: "Sleman",
    phone: "+62 274 864 771",
    whatsapp: "+62 813 9876 5432",
    operatingHours: "07:00 - 22:00 WIB",
    description:
      "Spesialis armada SUV tangguh dan MPV premium di Sleman Utara. Sangat cocok bagi wisatawan yang ingin menjelajah lereng Merapi, Kaliurang, maupun rute perbukitan Menoreh Kulon Progo.",
    avatarUrl:
      "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=300&q=80",
    bannerUrl:
      "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=80",
    establishedYear: 2019,
    coverageSpotIds: ["spot-sleman", "spot-yia", "spot-tugu"],
    features: [
      "Spesialis SUV Ground Clearance Tinggi",
      "Kondisi Ban & Rem Selalu Standar OEM",
      "Bebas Biaya Jemput Garasi Sleman",
      "Free Car Seat Anak (Request Dahulu)",
    ],
    reviews: [
      {
        id: "rev-03",
        authorName: "Rian Hidayat",
        authorCity: "Bandung",
        rating: 5,
        date: "20 September 2026",
        comment:
          "Xforce-nya jos gandos! Tanjakan Kaliurang libas enteng. Ground clearance tinggi bikin tenang lewat jalan berlubang. Unit sangat bersih.",
        vehicleName: "Mitsubishi Xforce Ultimate 1.5 CVT 2024",
        merchantReply: {
          author: "Agus Pratama (Sleman Auto)",
          date: "21 September 2026",
          comment:
            "Terima kasih Mas Rian! Xforce memang jagoan kami untuk rute perbukitan Jogja. Ditunggu kunjungan berikutnya nggih!",
        },
      },
    ],
  },
  {
    id: "rental-malioboro",
    name: "Malioboro Trans Mobility",
    slug: "malioboro-trans-mobility",
    nib: "1203000918231",
    nibVerified: true,
    rating: 4.95,
    totalReviews: 112,
    completedBookings: 472,
    address: "Jl. Dagen No. 18, Sosromenduran, Gedongtengen",
    district: "Gedongtengen",
    city: "Kota Yogyakarta",
    phone: "+62 274 512 889",
    whatsapp: "+62 811 2345 678",
    operatingHours: "24 Jam Non-Stop",
    description:
      "Pelopor armada ramah lingkungan Kendaraan Listrik (EV) dan City Car modern di jantung pariwisata Malioboro. Siap antar-jemput ke seluruh hotel bintang dan penginapan di DIY.",
    avatarUrl:
      "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=300&q=80",
    bannerUrl:
      "https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&w=1200&q=80",
    establishedYear: 2021,
    coverageSpotIds: ["spot-malioboro", "spot-tugu", "spot-yia"],
    features: [
      "Armada EV Ioniq 5 Baterai Penuh 100%",
      "Edukasi Pengisian SPKLU Jogja",
      "Layanan Antar Hotel Malioboro Gratis",
      "Fast Response 24 Jam via WhatsApp",
    ],
    reviews: [
      {
        id: "rev-04",
        authorName: "Jessica Tan",
        authorCity: "Tangerang",
        rating: 5,
        date: "12 September 2026",
        comment:
          "Nyobain Ioniq 5 keliling Jogja seru banget! Senyap, AC dingin, gak pusing antre bensin. Rental jelasin cara charge dengan sangat detail.",
        vehicleName: "Hyundai Ioniq 5 Signature Long Range 2024",
      },
    ],
  },
  {
    id: "rental-kencana",
    name: "Kencana Rent Jogja Selatan",
    slug: "kencana-rent-jogja-selatan",
    nib: "8120005189210",
    nibVerified: true,
    rating: 4.89,
    totalReviews: 64,
    completedBookings: 295,
    address: "Jl. Bantul Km 5.5, Pendowoharjo, Sewon",
    district: "Sewon",
    city: "Bantul",
    phone: "+62 274 646 220",
    whatsapp: "+62 815 6789 0123",
    operatingHours: "07:00 - 21:00 WIB",
    description:
      "Pilihan terpercaya untuk rental mobil hemat, City Car lincah, dan armada terawat untuk area Bantul, Kasongan, Parangtritis, dan Kota Jogja.",
    avatarUrl:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80",
    bannerUrl:
      "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&w=1200&q=80",
    establishedYear: 2020,
    coverageSpotIds: ["spot-bantul", "spot-tugu", "spot-lempuyangan"],
    features: [
      "Harga Ramah Wisatawan & Mahasiswa",
      "Brio RS Kondisi Prima & Irit",
      "Bebas Biaya Antar Area Sewon & Bantul",
    ],
    reviews: [
      {
        id: "rev-05",
        authorName: "Anindya Putri",
        authorCity: "Semarang",
        rating: 5,
        date: "5 September 2026",
        comment:
          "Brio-nya super lincah masuk gang-gang sentra keramik Kasongan. Pelayanan gercep dan proses deposit lancar!",
        vehicleName: "Honda Brio RS Urbanite Edition CVT 2023",
      },
    ],
  },
];

export function getVehicleById(id: string): Vehicle | undefined {
  return FEATURED_YOGYAKARTA_VEHICLES.find((v) => v.id === id);
}

export function getRentalById(id: string): import("@/types/domain").RentalPartner | undefined {
  return YOGYAKARTA_RENTAL_PARTNERS.find((r) => r.id === id);
}

export function getVehiclesByRentalId(rentalId: string): Vehicle[] {
  return FEATURED_YOGYAKARTA_VEHICLES.filter((v) => v.rentalId === rentalId);
}

export function getPickupSpotById(id: string): PickupSpot | undefined {
  return YOGYAKARTA_PICKUP_SPOTS.find((s) => s.id === id);
}

