"use client";

import { MitraNav } from "@/components/mitra/mitra-nav";
import { usePhase10Mitra } from "@/lib/store/phase10-mitra-store";
import { formatIndonesianDate, formatRupiah } from "@/lib/utils";
import { BadgeCheck, Banknote, CheckCircle2, Clock, Download, MessageSquare, ShieldCheck, Star, UserCheck, Wallet } from "lucide-react";
function Shell({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <div className="min-h-screen bg-slate-50 text-slate-800"><MitraNav currentTab="keuangan"/><main className="max-w-7xl mx-auto px-4 sm:px-6 py-6 space-y-6"><div><span className="inline-flex px-3 py-1 rounded-full bg-blue-50 text-blue-700 border border-blue-200 text-xs font-bold mb-3">Fase 10 Mitra</span><h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-slate-950">{title}</h1><p className="text-sm text-slate-500 mt-1 max-w-3xl">{subtitle}</p></div>{children}</main></div> }
function Card({children}: {children: React.ReactNode}) { return <section className="bg-white rounded-3xl border border-slate-200 p-6 shadow-xs">{children}</section> }
function Money({ value }: { value: number }) { return <span className="font-mono font-extrabold tabular-nums">{formatRupiah(value)}</span> }

export default function RekeningPage(){ const { bank, updateBank } = usePhase10Mitra(); return <Shell title="Pengaturan Rekening Bank Payout" subtitle="Kelola rekening tujuan pencairan dana mitra dengan prosedur verifikasi uji transfer mikro anti-fraud."><div className="grid lg:grid-cols-3 gap-6"><Card><BadgeCheck className="w-8 h-8 text-emerald-600"/><h2 className="font-extrabold text-slate-950 mt-4">{bank.verificationStatus.replaceAll("_"," ")}</h2><p className="text-sm text-slate-500 mt-2">Uji transfer mikro terakhir: Rp {bank.microDepositAmount}</p></Card><Card><h2 className="font-extrabold text-slate-950 mb-4">Data rekening</h2><div className="space-y-3"><input defaultValue={bank.bankName} className="w-full rounded-2xl border border-slate-200 p-3"/><input defaultValue={bank.accountNumber} className="w-full rounded-2xl border border-slate-200 p-3"/><input defaultValue={bank.accountHolder} className="w-full rounded-2xl border border-slate-200 p-3"/><button onClick={()=>updateBank({...bank, updatedAt:new Date().toISOString(), verificationStatus:"MENUNGGU_UJI_TRANSFER"})} className="w-full min-h-[44px] rounded-2xl bg-blue-600 text-white text-sm font-extrabold">Simpan & Mulai Uji Transfer</button></div></Card><Card><h2 className="font-extrabold text-slate-950">Kontrol keamanan</h2><p className="text-sm text-slate-600 mt-3">Perubahan rekening payout menahan pencairan baru sampai micro-deposit cocok dan diverifikasi.</p></Card></div></Shell> }
