"use client";

import { MitraNav } from "@/components/mitra/mitra-nav";
import { usePhase10Mitra } from "@/lib/store/phase10-mitra-store";
import { formatIndonesianDate, formatRupiah } from "@/lib/utils";
import { BadgeCheck, Banknote, CheckCircle2, Clock, Download, MessageSquare, ShieldCheck, Star, UserCheck, Wallet } from "lucide-react";
function Shell({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <div className="min-h-screen bg-slate-50 text-slate-800"><MitraNav currentTab="keuangan"/><main className="max-w-7xl mx-auto px-4 sm:px-6 py-6 space-y-6"><div><span className="inline-flex px-3 py-1 rounded-full bg-blue-50 text-blue-700 border border-blue-200 text-xs font-bold mb-3">Fase 10 Mitra</span><h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-slate-950">{title}</h1><p className="text-sm text-slate-500 mt-1 max-w-3xl">{subtitle}</p></div>{children}</main></div> }
function Card({children}: {children: React.ReactNode}) { return <section className="bg-white rounded-3xl border border-slate-200 p-6 shadow-xs">{children}</section> }
function Money({ value }: { value: number }) { return <span className="font-mono font-extrabold tabular-nums">{formatRupiah(value)}</span> }

export default function UlasanPage(){ const { reviews, replyReview } = usePhase10Mitra(); return <Shell title="Manajemen Reputasi & Balas Ulasan" subtitle="Pantau rating armada rental dan beri tanggapan resmi mitra secara profesional."><div className="grid gap-4">{reviews.map((r)=><Card key={r.id}><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-amber-500">{Array.from({length:r.rating}).map((_,i)=><Star key={i} className="w-4 h-4 fill-current"/>)}<span className="text-xs font-bold text-slate-500 ml-2">{r.bookingCode}</span></div><h2 className="font-extrabold text-slate-950 mt-2">{r.vehicleName}</h2><p className="text-sm text-slate-500">oleh {r.renterName} • {formatIndonesianDate(r.createdAt)}</p><p className="text-sm text-slate-700 mt-3">“{r.comment}”</p>{r.reply && <div className="mt-4 p-4 rounded-2xl bg-blue-50 border border-blue-100 text-sm text-blue-900"><b>Tanggapan mitra:</b> {r.reply}</div>}</div><button onClick={()=>replyReview(r.id, "Terima kasih atas ulasannya. Kami akan terus menjaga kualitas unit dan ketepatan layanan.")} className="min-h-[44px] px-4 rounded-2xl bg-blue-600 text-white text-xs font-extrabold">Balas Resmi</button></div></Card>)}</div></Shell> }
