"use client";

import { MitraNav } from "@/components/mitra/mitra-nav";
import { usePhase10Mitra } from "@/lib/store/phase10-mitra-store";
import { formatIndonesianDate, formatRupiah } from "@/lib/utils";
import { BadgeCheck, Banknote, CheckCircle2, Clock, Download, MessageSquare, ShieldCheck, Star, UserCheck, Wallet } from "lucide-react";
function Shell({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <div className="min-h-screen bg-slate-50 text-slate-800"><MitraNav currentTab="keuangan"/><main className="max-w-7xl mx-auto px-4 sm:px-6 py-6 space-y-6"><div><span className="inline-flex px-3 py-1 rounded-full bg-blue-50 text-blue-700 border border-blue-200 text-xs font-bold mb-3">Fase 10 Mitra</span><h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-slate-950">{title}</h1><p className="text-sm text-slate-500 mt-1 max-w-3xl">{subtitle}</p></div>{children}</main></div> }
function Card({children}: {children: React.ReactNode}) { return <section className="bg-white rounded-3xl border border-slate-200 p-6 shadow-xs">{children}</section> }
function Money({ value }: { value: number }) { return <span className="font-mono font-extrabold tabular-nums">{formatRupiah(value)}</span> }

export default function PelangganPage(){ const { customers } = usePhase10Mitra(); return <Shell title="Database Pelanggan Rental" subtitle="Daftar penyewa yang pernah menyewa agar tim mitra bisa mengenali pelanggan loyal, preferensi unit, dan catatan layanan."><div className="grid gap-4">{customers.map((c)=><Card key={c.id}><div className="flex flex-col md:flex-row md:items-center justify-between gap-4"><div className="flex items-center gap-4"><div className="w-12 h-12 rounded-2xl bg-blue-600 text-white flex items-center justify-center font-black">{c.name.slice(0,2).toUpperCase()}</div><div><h2 className="font-extrabold text-slate-950">{c.name}</h2><p className="text-sm text-slate-500">{c.phone} • {c.city}</p><p className="text-sm text-slate-600 mt-2">{c.notes}</p></div></div><div className="text-right"><span className="px-2 py-1 rounded-full bg-emerald-50 text-emerald-700 border border-emerald-200 text-xs font-bold">{c.riskLabel}</span><p className="text-sm mt-2"><b>{c.completedBookings}x</b> booking selesai</p><p className="text-sm"><Money value={c.totalSpend}/></p></div></div></Card>)}</div></Shell> }
