"use client";

import Link from "next/link";
import { MitraNav } from "@/components/mitra/mitra-nav";
import { useBookings } from "@/lib/store/booking-store";
import { usePhase10Mitra } from "@/lib/store/phase10-mitra-store";
import { formatIndonesianDate, formatRupiah } from "@/lib/utils";
import { Banknote, BadgeCheck, Car, CheckCircle2, Clock, Download, FileText, MessageSquare, ShieldCheck, Star, Upload, UserCheck, Wallet } from "lucide-react";

function Shell({ tab="keuangan", title, subtitle, children }: { tab?: any; title: string; subtitle: string; children: React.ReactNode }) { return <div className="min-h-screen bg-slate-50 text-slate-800"><MitraNav currentTab={tab}/><main className="max-w-7xl mx-auto px-4 sm:px-6 py-6 space-y-6"><div><span className="inline-flex px-3 py-1 rounded-full bg-blue-50 text-blue-700 border border-blue-200 text-xs font-bold mb-3">Fase 10 Mitra</span><h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-slate-950">{title}</h1><p className="text-sm text-slate-500 mt-1 max-w-3xl">{subtitle}</p></div>{children}</main></div> }
function Card({children}: {children: React.ReactNode}) { return <section className="bg-white rounded-3xl border border-slate-200 p-6 shadow-xs">{children}</section> }
function Money({ value }: { value: number }) { return <span className="font-mono font-extrabold tabular-nums">{formatRupiah(value)}</span> }

export default function CreateClaimPage(){ const { bookings } = useBookings(); const { createClaim } = usePhase10Mitra(); const b = bookings.find((x)=>x.status==="SELESAI") || bookings[0]; return <Shell tab="booking" title="Pengajuan Klaim Kerusakan Deposit" subtitle="Ajukan klaim dalam claim window 24 jam dengan bukti foto komparasi dan estimasi biaya yang transparan."><Card><div className="grid lg:grid-cols-2 gap-6"><div className="space-y-4"><label className="block text-xs font-bold text-slate-600">Booking terkait<input value={b.bookingCode} readOnly className="mt-1 w-full rounded-2xl border border-slate-200 p-3 bg-slate-50"/></label><label className="block text-xs font-bold text-slate-600">Kategori<select className="mt-1 w-full rounded-2xl border border-slate-200 p-3 bg-white"><option>Baret bodi</option><option>BBM kurang</option><option>Interior kotor</option></select></label><label className="block text-xs font-bold text-slate-600">Nominal klaim<input defaultValue="150000" className="mt-1 w-full rounded-2xl border border-slate-200 p-3"/></label><label className="block text-xs font-bold text-slate-600">Deskripsi<textarea defaultValue="Baret halus baru pada panel kanan depan setelah unit kembali." className="mt-1 w-full rounded-2xl border border-slate-200 p-3 min-h-28"/></label></div><div className="space-y-4"><div className="grid grid-cols-2 gap-3">{["Foto kerusakan", "Estimasi bengkel", "Foto awal", "Foto kembali"].map((x)=><div key={x} className="h-32 rounded-2xl border border-dashed border-slate-300 bg-slate-50 flex flex-col items-center justify-center text-xs font-bold text-slate-500"><Upload className="w-5 h-5 mb-2 text-blue-600"/>{x}</div>)}</div><button onClick={()=>createClaim({ bookingId:b.id, bookingCode:b.bookingCode, renterName:b.userName, vehicleName:b.vehicleName, licensePlate:b.licensePlate, category:"BARET_BODI", claimedAmount:150000, workshopEstimate:"Estimasi Tugu Detailing", description:"Baret halus baru pada panel kanan depan setelah unit kembali.", evidenceUrls:[] })} className="w-full min-h-[44px] rounded-2xl bg-blue-600 text-white text-sm font-extrabold">Ajukan Klaim ke Mediasi</button></div></div></Card></Shell> }
